name: Auto Merge Dev Branch

on:
  push:
    branches:
      - dev

jobs:
  merge_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: git config user.email "ashuzamaheshe4@gmail.com" && git config user.name "AshDest"

      - name: Merge Dev Branch
        run: |
          git checkout main
          git pull origin main
          git merge --no-ff ${{ github.sha }} -m "Auto-merge from GitHub Actions"
          git push origin main
