name: Auto Merge Dev Branch
on:
  push:
    branches:
      - dev
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge dev into master
        uses: pascalgn/automerge-action@v0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          commit-message: Automatic merge of dev into master
